INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('ammo_small', 'Weapon Clip', 1, 0, 1),
	('ammo_box', 'Weapon Box', 2, 0, 1),
	('ammo_pistol', 'Pistol Clip', 1, 0, 1),
	('ammo_smg', 'SMG Clip', 1, 0, 1),
	('ammo_shotgun', 'Shotgun Clip', 1, 0, 1),
	('ammo_rifle', 'Rifle Clip', 1, 0, 1),
	('ammo_mg', 'MG Clip', 1, 0, 1),
	('ammo_sniper', 'Sniper Clip', 1, 0, 1),
	('ammo_throwable', 'Throwable Clip', 1, 0, 1),
	('att_scope', 'att_scope', 1, 0, 1),
	('att_grip', 'att_grip', 1, 0, 1),
	('att_flashlight', 'att_flashlight', 1, 0, 1),
	('att_clip_extended', 'Extended Clip', 1, 0, 1),
	('att_suppressor', 'att_suppressor', 1, 0, 1),
	('att_luxary_finish', 'Luxury Finish', 1, 0, 1),
	('att_tint_green', 'Green', 1, 0, 1),
	('att_tint_gold', 'Gold', 1, 0, 1),
	('att_tint_pink', 'Pink', 1, 0, 1),
	('att_tint_camouflag', 'Army', 1, 0, 1),
	('att_tint_blue', 'LSPD', 1, 0, 1),
	('att_tint_orange', 'Orange', 1, 0, 1),
	('att_tint_platinum', 'Platinum', 1, 0, 1)
;